[server]
headless = true
port = 7860
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 7860

[runner]
magicEnabled = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
